### ISSUE TITLE
OSError: Header missing END card

### ISSUE THREAD

**Issue by hippke** [afeinstein20/eleanor#169] opened 2020-03-21 16:26 UTC
Thanks for your help in the previous issue. I now encounter a different issue.
I am using the latest version of eleanor, astropy, astroquery, numpy.
I have flushed the content of the cache (`/home/michael/.eleanor/`) completely.
I try to download data for a star with coordinates. Minimal example:
```
import numpy as np
import eleanor
from astropy import units as u
from astropy.coordinates import SkyCoord
print(eleanor.__version__)
coords = SkyCoord(ra="06:11:43.72", dec="-04:39:55.6", unit=(u.hourangle, u.deg))
star = eleanor.Source(coords=coords)
data = eleanor.TargetData(star, do_pca=True)
```
I get the following error:
```
1.0.3
Downloading URL https://mast.stsci.edu/tesscut/api/v0.1/astrocut?ra=68.95970833333332&dec=-64.02703611111112&y=31&x=31&units=px&sector=6 to ./tesscut_20200321172144.zip ... [Done]
Inflating...
This is the first light curve you have made for this sector. Getting eleanor metadata products for Sector  6...
This will only take a minute, and only needs to be done once. Any other light curves you make in this sector will be faster.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   157  100   157    0     0      2      0  0:01:18  0:01:05  0:00:13    37
Target Acquired
Cadences Calculated
Traceback (most recent call last):
  File "/home/michael/miniconda3/envs/hpk_env/lib/python3.7/site-packages/astropy/io/fits/hdu/base.py", line 406, in _readfrom_internal
    header_str, header = _BasicHeader.fromfile(data)
  File "/home/michael/miniconda3/envs/hpk_env/lib/python3.7/site-packages/astropy/io/fits/header.py", line 2077, in fromfile
    header_str, cards = parse_header(fileobj)
  File "astropy/io/fits/_utils.pyx", line 36, in astropy.io.fits._utils.parse_header
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/michael/Desktop/temp_tess/debug_eleanor.py", line 7, in <module>
    star = eleanor.Source(coords=coords)
  File "/home/michael/miniconda3/envs/hpk_env/lib/python3.7/site-packages/eleanor/source.py", line 232, in __init__
    Update(sector=self.sector)
  File "/home/michael/miniconda3/envs/hpk_env/lib/python3.7/site-packages/eleanor/update.py", line 124, in __init__
    self.get_quality()
  File "/home/michael/miniconda3/envs/hpk_env/lib/python3.7/site-packages/eleanor/update.py", line 244, in get_quality
    twoMin     = fits.open(shortCad_fn)
  File "/home/michael/miniconda3/envs/hpk_env/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 158, in fitsopen
    lazy_load_hdus, **kwargs)
  File "/home/michael/miniconda3/envs/hpk_env/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 397, in fromfile
    lazy_load_hdus=lazy_load_hdus, **kwargs)
  File "/home/michael/miniconda3/envs/hpk_env/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 1071, in _readfrom
    read_one = hdulist._read_next_hdu()
  File "/home/michael/miniconda3/envs/hpk_env/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 1146, in _read_next_hdu
    hdu = _BaseHDU.readfrom(fileobj, **kwargs)
  File "/home/michael/miniconda3/envs/hpk_env/lib/python3.7/site-packages/astropy/io/fits/hdu/base.py", line 327, in readfrom
    **kwargs)
  File "/home/michael/miniconda3/envs/hpk_env/lib/python3.7/site-packages/astropy/io/fits/hdu/base.py", line 414, in _readfrom_internal
    endcard=not ignore_missing_end)
  File "/home/michael/miniconda3/envs/hpk_env/lib/python3.7/site-packages/astropy/io/fits/header.py", line 514, in fromfile
    padding)[1]
  File "/home/michael/miniconda3/envs/hpk_env/lib/python3.7/site-packages/astropy/io/fits/header.py", line 596, in _from_blocks
    raise OSError('Header missing END card.')
OSError: Header missing END card.
```

**Comment by hippke** [comment] 2020-03-21 17:42
I have setup a new fresh conda environment and pulled all new packages. Now, the error message is different:
```
1.0.3
Downloading URL https://mast.stsci.edu/tesscut/api/v0.1/astrocut?ra=68.95970833333332&dec=-64.02703611111112&y=31&x=31&units=px&sector=6 to ./tesscut_20200321183229.zip ... [Done]
Inflating...
This is the first light curve you have made for this sector. Getting eleanor metadata products for Sector  6...
This will only take a minute, and only needs to be done once. Any other light curves you make in this sector will be faster.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
CBVs Made
Success! Sector  6 now available.
Downloading URL https://mast.stsci.edu/api/v0.1/Download/file?uri=mast:HLSP/eleanor/postcards/s0006/1-1/hlsp_eleanor_tess_ffi_postcard-s0006-1-1-cal-1196-0322_tess_v2_bkg.fits to /home/michael/.eleanor/mastDownload/HLSP/hlsp_eleanor_tess_ffi_postcard-s0006-1-1-cal-1196-0322_tess_v2_pc/hlsp_eleanor_tess_ffi_postcard-s0006-1-1-cal-1196-0322_tess_v2_bkg.fits ... [Done]
Downloading URL https://mast.stsci.edu/api/v0.1/Download/file?uri=mast:HLSP/eleanor/postcards/s0006/1-1/hlsp_eleanor_tess_ffi_postcard-s0006-1-1-cal-1196-0322_tess_v2_pc.fits to /home/michael/.eleanor/mastDownload/HLSP/hlsp_eleanor_tess_ffi_postcard-s0006-1-1-cal-1196-0322_tess_v2_pc/hlsp_eleanor_tess_ffi_postcard-s0006-1-1-cal-1196-0322_tess_v2_pc.fits ... [Done]
Downloading URL https://mast.stsci.edu/api/v0.1/Download/file?uri=mast:HLSP/eleanor/postcards/s0006/1-1/hlsp_eleanor_tess_ffi_postcard-s0006-1-1_tess_v2_pm.txt to /home/michael/.eleanor/mastDownload/HLSP/hlsp_eleanor_tess_ffi_postcard-s0006-1-1-cal-1196-0322_tess_v2_pc/hlsp_eleanor_tess_ffi_postcard-s0006-1-1_tess_v2_pm.txt ... [Done]
WARNING: FITSFixedWarning: 'datfix' made the change 'Set MJD-OBS to 58467.775828 from DATE-OBS.
Set DATE-BEG to '2018-12-15T18:38:20.689' from MJD-BEG'. [astropy.wcs.wcs]
WARNING: The "exact" method is not yet implemented for rectangular apertures -- using "subpixel" method with "subpixels=32" [photutils.aperture.core]
Traceback (most recent call last):
  File "/home/michael/Desktop/temp_tess/debug_eleanor.py", line 8, in <module>
    data = eleanor.TargetData(star, do_pca=True)
  File "/home/michael/miniconda3/envs/hpk_env/lib/python3.7/site-packages/eleanor/targetdata.py", line 210, in __init__
    self.get_lightcurve()
  File "/home/michael/miniconda3/envs/hpk_env/lib/python3.7/site-packages/eleanor/targetdata.py", line 564, in get_lightcurve
    ap_size = np.nansum(self.all_apertures, axis=(1,2))
  File "<__array_function__ internals>", line 6, in nansum
  File "/home/michael/miniconda3/envs/hpk_env/lib/python3.7/site-packages/numpy/lib/nanfunctions.py", line 649, in nansum
    a, mask = _replace_nan(a, 0)
  File "/home/michael/miniconda3/envs/hpk_env/lib/python3.7/site-packages/numpy/lib/nanfunctions.py", line 102, in _replace_nan
    mask = np.not_equal(a, a, dtype=bool)
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by hippke** [comment] 2020-03-21 19:22
Is the problem perhaps with the tensorflow version? The `setup.py` requires `tensorflow<=1.14` which refuses to install in conda-Python 3.8. So I used the 2.2 version. Is version <= 1.14 essential?

**Comment by benmontet** [comment] 2020-03-25 11:38
Hmm, this works fine for me. It shouldn't be an issue with tensorflow, that's only used in the PSF modeling (and that module requires tf<2.0, they've made some significant not-backward compatible changes that I haven't had a chance to address yet) but it's safe for everything else, and since you're not setting do_psf=True I don't think it's even importing tensorflow.

1) What system architecture are you using?
2) Can you please run the following from the command line and send the output:
```python -m tess_stars2px -c 92.93216666666666 -4.665444444444445```

that will give the tess-point output for these coordinates which might give a hint to me...

**Comment by hippke** [comment] 2020-03-25 12:38
Thank you for your assistance in sorting this out! 
1. I'm on Ubuntu + conda; Python 3.8 64-bit Linux
2. `python -m tess_stars2px -c 92.93216666666666 -4.665444444444445`
```
# TIC     |   RA      |   Dec     | EclipticLong | EclipticLat | Sector | Camera | Ccd | ColPix | RowPix
000000000 |  92.932167 |  -4.665444 |  93.308650 | -28.072616 |  6 | 1 | 2 |   46.586 |  357.452
000000000 |  92.932167 |  -4.665444 |  93.308650 | -28.072616 | 33 | 1 | 1 | 1174.112 |  330.491
```

**Comment by benmontet** [comment] 2020-03-26 23:39
Okay I believe it should work now!

There was a bug when ```eleanor.Source()``` was called without the desired sector being passed through, in cases where future sectors are already loaded into tess-point, in that it was still reading in the pixel coordinates from future sectors. In this particular case passing through ```eleanor.Source(coords=coords, sector=6)``` would work (which is why I wasn't seeing it originally), but just passing in coords would then search at 1-1-1174-330 and it would get confused and break.

That's now sorted in the latest version in the repo, so please update to that version and make sure it works for you!

I was able to reproduce the bug and the current version produces a light curve, so I'm going to close this issue but if you continue to have this issue please do re-open it.

BTW note that this particular target is 2.5 pixels from the edge of the detector (columns start at 44), so part of the star's PSF is falling off the detector so the photometry is not great for this star, it has worse position-dependent effects than usual as photons are missing the CCD.

**Closed by benmontet** 2020-03-26 23:39 UTC
