### ISSUE TITLE
S23 tesscut failures

### ISSUE THREAD

**Issue by ethankruse** [afeinstein20/eleanor#175] opened 2020-05-19 00:45 UTC
Hi,

Brian is telling me that we're seeing a huge increase in TessCut light curve failures in S23 and I'm a bit stumped. Here's a TIC that reproduces it:
`star=eleanor.Source(tic=236708567,tc=True,sector=23)
data=eleanor.TargetData(star,do_psf=False,do_pca=True)`

You end up with a failure in the `get_lightcurve` function. I've managed to trace it back to a problem with the apertures, but that's as far as I can get. When I look at the traceback, I'm finding that the `self.all_apertures` list is full of 0 arrays. I'm assuming those are supposed to contain apertures of various shapes/sizes for testing with numbers from 0-1 depending on how much to use that pixel in the aperture. But if it's all 0 that ends up meaning in `get_lightcurve` that all fluxes and errors are 0 because you're not using any pixels and then everything breaks.

Any idea what's going on? Is this really a S23 issue somehow?

**Comment by benmontet** [comment] 2020-05-21 06:04
Okay yes I can reproduce this. Strange! This is a new one for me.

Have you seen this in other sectors or is this new to S23? Do you have a rough fraction of targets for which this happens?

**Comment by benmontet** [comment] 2020-05-21 06:42
Okay it's sorted.

The issue was because at the start of this sector there are ~three dozen cadences with `quality == 0` but all flux values equal to zero across the TPF. The software builds apertures, then checks to see if any of these apertures have exactly zero flux, because that's the behaviour of an aperture drawn over the edge of the detector and that helps with detrending those objects (which we learned dealing with that CBP in that sector). If a pixel has a flux of zero, it's then deleted from all apertures.

Previously it was checking just the zeroth cadence, and since every pixel was zero, every pixel was removed from each aperture. I've changed this to (a) use the median of all cadences and (b) if all pixels are zero on a cadence, assign it a nonzero quality flag. 

I'm reasonably confident the problem is sorted with these changes so I'm going to close the issue; if this wasn't the fix and you're still having issues then please re-open and we can dig in further!

Also: It looks like the scattered light is quite bad around 1945 in a way that isn't quality flagged either, you may want to experiment with appending on your own quality flags and running `get_lightcurve` with those if you're finding strange results in the second orbit!

-B

@afeinstein20 we should push these changes to the pypi version because this will mess up anyone trying to make a LC for S23, and also there are enough other fixes from the past couple months that it's probably time to push them along. I've already updated the changelog so you should just need to bump the version number and push it over.

**Closed by benmontet** 2020-05-21 06:42 UTC
