### ISSUE TITLE
eleanor not finding data for star with multi-sector coverage

### ISSUE THREAD

**Issue by jkcarlberg** [afeinstein20/eleanor#230] opened 2021-05-26 16:52 UTC
I am running eleaor 2.0.3. One of the stars I am interested in (TIC 35725282) has coverage by TESS in 2 sectors, as confirmed by TESSCut:
<img width="660" alt="Screen Shot 2021-05-26 at 12 48 48 PM" src="https://user-images.githubusercontent.com/20912889/119700115-d9f6e780-be20-11eb-8c77-ef67410b8ad7.png">

However, when I try to retrieve the data using eleanor I receive the following error:
<img width="1341" alt="Screen Shot 2021-05-26 at 12 48 30 PM" src="https://user-images.githubusercontent.com/20912889/119700181-e8450380-be20-11eb-9228-8889e4dd74f8.png">

I have tested some other TIC IDs that appear to work correctly, including one that required a TESScut download because no eleanor postcard yet existed, so I am not sure why this particular target is causing an error.

**Comment by benmontet** [comment] 2021-05-26 23:43
Hey, 

Yes, I can reproduce this and I think I understand what's going on!

If I call `tess-point` on this target I get an equivalent warning that this star is not observed by TESS:

![image](https://user-images.githubusercontent.com/1314530/119744369-34e71800-becf-11eb-86ba-a2268060ffb2.png)

`tess-point` restricts more forcefully than TESSCut about what qualifies as being observed by TESS. I have a hacked version of tess-point where it returns pixel locations of stars near the detector and it gives for this target:

![image](https://user-images.githubusercontent.com/1314530/119744465-71b30f00-becf-11eb-8530-e603fe413a1e.png)

Sectors 4 and 31 like you suggest. The issue is that it falls on row 2077 and row 2091 on the detector in those two sectors. The detector has 2078 rows but only 1-2048 are actually exposed to the sky, others are used for various calibrations:

![image](https://user-images.githubusercontent.com/1314530/119744587-ad4dd900-becf-11eb-9c31-b61898954c5e.png)

So this star actually has not been observed by TESS! I think our behaviour is correct here and TESSCut's is wrong, but it does report stars falling on the detector if they're just a few pixels off, which has caused confusion before. 

You can check this by running the TESSCut scheme for this star and checking what the file you get is, I believe it'll just be noise and/or NaNs, no star. Let me know if that isn't the case and I can dig in to try to find out what else might be going on, but I'm pretty sure that's the issue here!

**Comment by jkcarlberg** [comment] 2021-05-28 17:52
Thanks for investigating!  Indeed, if I retrieve data from TESScut and look at the raw counts, it is all [-1]. I had originally scanned the TESScut data just at the 'FLUX' column and saw a bunch of "real" numbers in addition to nan's, so my initial quick look made me think it was ok.

**Comment by benmontet** [comment] 2021-05-29 01:04
Fantastic! Well, bummer for your star but glad we could understand what's going on. I'll go ahead and close the issue, feel free to re-open or create a new one if you run into other troubles using eleanor.

**Closed by benmontet** 2021-05-29 01:04 UTC
