### ISSUE TITLE
Problems with TargetData 

### ISSUE THREAD

**Issue by lrisa** [afeinstein20/eleanor#75] opened 2019-04-24 18:33 UTC
Hi all, I am following the tutorial and when I reach the sentence data = eleanor.TargetData(star, height=15, width=15, bkg_size=31, do_psf=True, do_pca=True) the following errors appear. I am not sure what's going on. I have python 3.6.7. Hope you can help me. Thank you.  
<img width="1273" alt="Screen Shot 2019-04-23 at 7 21 00 PM" src="https://user-images.githubusercontent.com/49927180/56684381-3fea7100-6695-11e9-80b3-c5b9f4122e74.png">

**Comment by benmontet** [comment] 2019-04-24 18:41
Hi Irisa,

Did you clone the repository from github or install it via pip? We're just about to make some upgrades and there might be a bug in the latest development version on here.

If you cloned it from here, can you remove it and instead install it either via pip (pip install eleanor), or instead clone this version: (https://github.com/afeinstein20/eleanor/tree/5787ed12c16f8c377173fba130af9cefaab22c7f) and let us know if that solves the issue?

**Comment by lrisa** [comment] 2019-04-24 18:51
I cloned it yesterday from github, but if you are making changes now, maybe I should reinstall it. Thank you!

**Comment by benmontet** [comment] 2019-04-24 18:54
Yes I bet that's the issue then! Please clone the version I linked above (or install via pip) and let us know if that works.

**Comment by lrisa** [comment] 2019-04-24 23:01
Ok, I have used the eleanor version you suggested with python3.6.7 and gave me an error like this "libc++abi.dylib: terminating with uncaught exception of type NSException", which apparently is due to the 3.6.7 version of python. Then, I made a new env for python 3.6.8 and compiled eleanor. It went a bit further than in my first post (it even displayed a plot), but there are still some bugs that makes it crash. So I wonder whether it's a problem of python versions, maybe I should use an older than 3.6.7. 
<img width="1270" alt="Screen Shot 2019-04-24 at 5 49 37 PM" src="https://user-images.githubusercontent.com/49927180/56699194-2ad40900-66ba-11e9-8a9b-1e9a367f23a8.png">

**Comment by benmontet** [comment] 2019-04-25 03:58
@afeinstein20 did I point to the wrong version? What's the most updated version that has the "traditional" background models?

We need to be putting all the testing, anything that would break the methods used in the quickstart tutorial, in a separate branch moving forward.

**Comment by afeinstein20** [comment] 2019-04-29 13:28
Hi Irisa, Could you please try pulling this version?
https://github.com/afeinstein20/eleanor/tree/3d8646627a7db35d61e4c70ce813760e9541edf4

Also, could I please get the TIC/Gaia ID or coordinates that you are using to make the eleanor.Source object? I'm wondering if I could recreate the issue. Thanks!

**Comment by lrisa** [comment] 2019-04-29 17:03
Thanks, I will try with that version. The object I used is the one of the example, tic=38846515.

**Comment by lrisa** [comment] 2019-04-29 19:40
A question, what version of python do you use to run eleanor?

**Comment by benmontet** [comment] 2019-04-29 19:45
I have used 3.4, 3.5, and 3.6. I believe numpy >= 1.16 is a requirement, although it might be 1.14, this is off the top of my head.

**Comment by SimonJMurphy** [comment] 2019-07-30 06:23
Bump.

Python version 3.6.5. Also using the example star. Tried using TIC number and coords.

Tried both pip install version and tried git cloning the version above.

With pip version I get the error:
<img width="1124" alt="eleanor_pip_error" src="https://user-images.githubusercontent.com/509713/62105563-1705f780-b2e6-11e9-8986-605340f0f55f.png">

And with git clone I get the different error:
<img width="1122" alt="eleanor_clone_error" src="https://user-images.githubusercontent.com/509713/62105562-1705f780-b2e6-11e9-90e1-d683fea26fd3.png">

Thanks for looking into this.

**Comment by benmontet** [comment] 2019-07-30 11:51
The pip one looks like a tensorflow compatibility issue with some code I just changed to avoid a future deprecation warning!

What version of tensorflow are you using? Can you upgrade to (I think) 1.14 and try again?

For the second one this looks like the same issue/solution:  https://github.com/enthought/comtypes/issues/102
https://github.com/enthought/comtypes/commit/98f6a42e8b452c67a65848d1c4476fb37df2aaa 

I’m also using 3.6 so I’m not sure what the culprit is exactly, but @afeinstein20 this should be straightforward to implement the same fix they use, no? It’s only adding a couple lines.

**Comment by SimonJMurphy** [comment] 2019-07-31 05:10
Thanks! I can confirm it was a tensorflow (and dependencies) issue.
I couldn't
`pip install tensorflow --upgrade`
so I had to
`conda update conda`
and
`conda update --all`
and do a lot of pip uninstalling and pip installing. I got there though!

Enjoying creating lightcurves with eleanor now :)

**Comment by benmontet** [comment] 2019-07-31 13:44
Great, glad you got it sorted! Closing this for now; if any other issues come up do re-open or open a new one as appropriate.

**Closed by benmontet** 2019-07-31 13:44 UTC
