### ISSUE TITLE
problem with eleanor.TargetData(): HTTP Error 404

### ISSUE THREAD

**Issue by barbara2015** [afeinstein20/eleanor#165] opened 2020-03-17 15:44 UTC
Dear all,
In some cases (not always) I get an error with eleanor.TargetData() and I do not know why and what to do. For example:

star = eleanor.Source(tic=147796121,tc=True)
data = eleanor.TargetData(star, height=15, width=15, bkg_size=31, do_psf=False, do_pca=False)
...
HTTPError: HTTP Error 404: Not Found
Could you please help me? Thanks a a lot.

**Comment by afeinstein20** [comment] 2020-03-17 16:14
Hi @barbara2015 ! Can you please post the entire issue you you received? Either copy & pasting it in or a screenshot would be great. Thanks!

**Comment by barbara2015** [comment] 2020-03-17 17:09
Thanks for your response. Here it is:
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-34-83245fc0db80> in <module>()
----> 1 data = eleanor.TargetData(star, height=15, width=15, bkg_size=31, do_psf=False, do_pca=False)

/anaconda3/lib/python3.6/site-packages/eleanor/targetdata.py in __init__(self, source, height, width, save_postcard, do_pca, do_psf, bkg_size, crowded_field, cal_cadences, try_load, language)
    171                     self.post_obj = Postcard_tesscut(source.cutout)
    172 
--> 173                 self.ffiindex = self.post_obj.ffiindex
    174                 self.flux_bkg = self.post_obj.bkg
    175                 self.get_time(source.coords)

/anaconda3/lib/python3.6/site-packages/eleanor/postcard.py in ffiindex(self)
    348     def ffiindex(self):
    349         sector = self.header['SECTOR']
--> 350         array_obj = urlopen('https://archipelago.uchicago.edu/tess_postcards/metadata/s{0:04d}/cadences_s{0:04d}.txt'.format(sector))
    351         A = [int(x) for x in array_obj.read().decode('utf-8').split()]
    352         return A

/anaconda3/lib/python3.6/urllib/request.py in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    221     else:
    222         opener = _opener
--> 223     return opener.open(url, data, timeout)
    224 
    225 def install_opener(opener):

/anaconda3/lib/python3.6/urllib/request.py in open(self, fullurl, data, timeout)
    530         for processor in self.process_response.get(protocol, []):
    531             meth = getattr(processor, meth_name)
--> 532             response = meth(req, response)
    533 
    534         return response

/anaconda3/lib/python3.6/urllib/request.py in http_response(self, request, response)
    640         if not (200 <= code < 300):
    641             response = self.parent.error(
--> 642                 'http', request, response, code, msg, hdrs)
    643 
    644         return response

/anaconda3/lib/python3.6/urllib/request.py in error(self, proto, *args)
    568         if http_err:
    569             args = (dict, 'default', 'http_error_default') + orig_args
--> 570             return self._call_chain(*args)
    571 
    572 # XXX probably also want an abstract factory that knows when it makes

/anaconda3/lib/python3.6/urllib/request.py in _call_chain(self, chain, kind, meth_name, *args)
    502         for handler in handlers:
    503             func = getattr(handler, meth_name)
--> 504             result = func(*args)
    505             if result is not None:
    506                 return result

/anaconda3/lib/python3.6/urllib/request.py in http_error_default(self, req, fp, code, msg, hdrs)
    648 class HTTPDefaultErrorHandler(BaseHandler):
    649     def http_error_default(self, req, fp, code, msg, hdrs):
--> 650         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    651 
    652 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 404: Not Found

**Comment by afeinstein20** [comment] 2020-03-17 19:46
Awesome, thanks for sending this! What version os eleanor are you running? The URL it's trying to call is part of an older setup. So my guess would be if you upgrade eleanor with `pip install eleanor --upgrade` this will solve the issue!

**Comment by barbara2015** [comment] 2020-03-18 10:42
Thanks a lot Adina for your answer. 
I have upgraded Eleanor to last version and I get a different error now. Apparently my target (07 21 53.4484 +71 20 36.363) has not been observed yet, but the data are present in the MAST archive!

---------------------------------------------------------------------------
SearchError                               Traceback (most recent call last)
<ipython-input-4-69ce5f86b5c9> in <module>()
----> 1 star = eleanor.Source(tic=147796121,tc=True)
      2 
      3 print('Found TIC {0} (Gaia {1}), with TESS magnitude {2}, RA {3}, and Dec {4}'
      4      .format(star.tic, star.gaia, star.tess_mag, star.coords[0], star.coords[1]))

/anaconda3/lib/python3.6/site-packages/eleanor/source.py in __init__(self, tic, gaia, coords, name, fn, sector, fn_dir, tc, local, post_dir, pm_dir)
    226                 self.tess_mag = self.tess_mag[0]
    227 
--> 228             self.locate_on_tess()
    229             self.tesscut_size = 31
    230 

/anaconda3/lib/python3.6/site-packages/eleanor/source.py in locate_on_tess(self)
    267         # tess_stars2px returns array [-1] when star not observed yet
    268         if len(sectors) < 1 or sectors[0] == np.array([-1]):
--> 269             raise SearchError("Tess has not (yet) observed your target.")
    270 
    271         else:

SearchError: Tess has not (yet) observed your target.

**Comment by benmontet** [comment] 2020-03-18 11:45
Ah, yes, I see the bug here. The issue is the star has been observed in some sectors but also will be observed in future sectors, and I believe the default behavior is to search for the latest possible sector (thinking most stars are observed in only one sector). In your case that's sector 26, when this star will also be re-observed, which of course there's no data yet for.

I think I see how we can fix this, but without waiting around for us, temporarily you can work around this in one of two ways:

1) Specifically pass through the sector you want. In your case: ```star = eleanor.Source(tic=147796121, tc=True, sector=20)```

2) Use multi_sectors: ```stars = eleanor.multi_sectors(tic=147796121, tc=True, sectors='all')```. You may need to run eleanor.Update(sector=20) before doing this one.

**Comment by barbara2015** [comment] 2020-03-18 13:14
Thanks a lot, you are great! Now it works!

**Comment by afeinstein20** [comment] 2020-03-18 14:08
Awesome! Thanks @benmontet for helping out :) I'm going to leave this open so we remember to fix this bug for eleanor.Source()

**Comment by benmontet** [comment] 2020-03-27 00:31
This should now work properly with the latest version, passing in ```star = eleanor.Source(tic=147796121,tc=True)``` seems to work fine now so I'm going to close this! (And that light curve looks really interesting!)

**Closed by benmontet** 2020-03-27 00:31 UTC
