### ISSUE TITLE
bitwise_or not supported error

### ISSUE THREAD

**Issue by doccosmos** [afeinstein20/eleanor#214] opened 2021-01-07 23:13 UTC
I'm trying to create a light curve from TESS data:

> star = eleanor.multi_sectors(coords = coord, sectors = 'all')
[...lots of files downloaded...]
No eleanor postcard has been made for your target (yet). Using TessCut instead.
> print(star)
[<eleanor.source.Source object at 0x7fdda892d450>, <eleanor.source.Source object at 0x7fddc1e1df10>, <eleanor.source.Source object at 0x7fddb16ba150>, <eleanor.source.Source object at 0x7fddb16d4dd0>, <eleanor.source.Source object at 0x7fddc18ec310>, <eleanor.source.Source object at 0x7fddc18fb890>, <eleanor.source.Source object at 0x7fddc18fb850>, <eleanor.source.Source object at 0x7fdda17c5ed0>, <eleanor.source.Source object at 0x7fddc194d4d0>, <eleanor.source.Source object at 0x7fddc18fb9d0>, <eleanor.source.Source object at 0x7fddc18fcc10>, <eleanor.source.Source object at 0x7fddb14021d0>]
> for s in star:
...   datum = eleanor.TargetData(s, height=15, width=15, bkg_size=31, do_psf=False, do_pca=False)
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/mjg/Projects/enchiridion/code/packages/tess/lib/python3.7/site-packages/eleanor/targetdata.py", line 225, in __init__
    self.set_quality()
  File "/Users/mjg/Projects/enchiridion/code/packages/tess/lib/python3.7/site-packages/eleanor/targetdata.py", line 797, in set_quality
    self.quality = np.bitwise_or(self.quality, bkgmask.mask * 2**18)
TypeError: ufunc 'bitwise_or' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

This is using eleanor 2.0.1 with Python 3.7.4

**Comment by benmontet** [comment] 2021-01-11 02:47
This is a new one to me! Does it happen for you with just this star or for all stars? If it's just this one can you include here (or via email, or whatever) a working example that reproduces this error so we can do an apples-to-apples comparison on the same star and sector and see if it's something specific to one star/one part of the sky?

**Comment by AlexanderEvitt** [comment] 2021-01-11 22:51
I'm having an identical error. I've tried it with a few different objects (blazars from 4FGL), all with Gaia IDs and found with eleanor using coordinates. Here's some code for replication:

```
star = eleanor.multi_sectors(sectors='all',tic=0,gaia=0,coords=(110.4727019394034,71.34343433315212),tc=True)

full_lc = lk.LightCurve([],[])
for observation in star:
    data = eleanor.TargetData(observation,bkg_size=15,do_pca=False)
    data.custom_aperture(shape='rectangle', h=1,w=1, method='exact')
    data.get_lightcurve()
```

This code produces the same error that the user above was having. I'm using the latest version of eleanor, but installed without the dependency fitsio to make it work on Windows 10 (the fitsio dependency breaks Windows installs AFAIK, but I can't see anywhere in the actual package where it is needed?). Every other dependency seems to be what eleanor requires. Numpy is v1.19.5, which might be relevant here.

**Comment by benmontet** [comment] 2021-01-12 00:14
Okay, thanks! I'll play with it. Your code runs fine for me, also with numpy 1.19.5, so let me dig a little and see what else might cause this. At the error, in debug mode can you check out what self.quality and bkgmask.mask are? Actually can you test all of the following, which will give me some information as to what part of this equation is struggling:

```
ipdb> self.quality
array([160., 128., 128., ...,   0.,   0.,   0.])
ipdb> type(self.quality)
<class 'numpy.ndarray'>
ipdb> len(self.quality)
1188
ipdb> bkgmask.mask
array([False, False, False, ..., False, False, False])
ipdb> type(bkgmask.mask)
<class 'numpy.ndarray'>
ipdb> len(bkgmask.mask)
1188
ipdb> bkgmask.mask * 2**18
array([0, 0, 0, ..., 0, 0, 0])
```

Thanks!

**Comment by doccosmos** [comment] 2021-01-16 03:28
I'm getting the same error with numpy 1.18.0

**Comment by doccosmos** [comment] 2021-01-16 03:48
self.quality: [0. 0. 0. ... 0. 0. 0.]
type(self.quality): <class 'numpy.ndarray'>
len(self.quality): 1130
bkgmask.mask: [False False False ... False False False]
len(bkgmask.mask): 1130
bkgmask.mask * 2**18: [0 0 0 ... 0 0 0]

**Comment by doccosmos** [comment] 2021-01-16 06:37
The fix is line 797, targetdata.py:

self.quality = np.bitwise_or(self.quality.astype(int), (bkgmask.mask * 2**18).astype(int))

**Comment by benmontet** [comment] 2021-01-17 22:37
It's still not obvious to me why the same set of calls works fine on my system but not over there, what function changed their typing rules behind the scenes, but I agree that will solve it and won't cause any other issues. 

I've made that change, it's now live on the github version and will get propagated through into the pip version next time we do a version update.

I'm therefore going to close this issue, if you're still having this issue do feel free to reopen it.

Thank you both!

**Closed by benmontet** 2021-01-17 22:37 UTC
